BALANCESHEET_KEYWORDS = [
                        'Total Assets',
                        'Current Assets',
                        'Cash, Cash Equivalents & Short Term Investments',
                        'Cash And Cash Equivalents',
                        'Receivables',
                        'Accounts receivable',
                        'Gross Accounts Receivable',
                        'Allowance For Doubtful Accounts Receivable',
                        'Other Receivables',
                        'Inventory',
                        'Raw Materials',
                        'Finished Goods',
                        'Other Current Assets',
                        'Total non-current assets',
                        'Net PPE',
                        'Gross PPE',
                        'Properties',
                        'Land And Improvements',
                        'Buildings And Improvements',
                        'Machinery Furniture Equipment',
                        'Construction in Progress',
                        'Accumulated Depreciation',
                        'Goodwill And Other Intangible Assets',
                        'Goodwill',
                        'Other Intangible Assets',
                        'Investments And Advances',
                        'Long Term Equity Investment',
                        'Investments in Subsidiariesat Cost',
                        'Non Current Deferred Assets',
                        'Non Current Deferred Taxes Assets',
                        'Other Non Current Assets',
                        'Total Liabilities Net Minority Interest',
                        'Current Liabilities',
                        'Payables And Accrued Expenses',
                        'Payables',
                        'Accounts Payable',
                        'Total Tax Payable',
                        'Income Tax Payable',
                        'Dividends Payable',
                        'Current Accrued Expenses',
                        'Pension & Other Post Retirement Benefit Plans Current',
                        'Current Debt And Capital Lease Obligation',
                        'Current Debt',
                        'Commercial Paper',
                        'Line of Credit',
                        'Other Current Borrowings',
                        'Other Current Liabilities',
                        'Total Non Current Liabilities Net Minority Interest',
                        'Long Term Debt And Capital Lease Obligation',
                        'Long Term Debt',
                        'Non Current Deferred Liabilities',
                        'Non Current Deferred Taxes Liabilities',
                        'Tradeand Other Payables Non Current',
                        'Employee Benefits',
                        'Other Non Current Liabilities',
                        'Total Equity Gross Minority Interest',
                        "Stockholders' Equity",
                        'Capital Stock',
                        'Common Stock',
                        'Additional Paid in Capital',
                        'Retained Earnings',
                        'Treasury Stock',
                        'Gains Losses Not Affecting Retained Earnings',
                        'Minority Interest',
                        'Total Capitalization',
                        'Common Stock Equity',
                        'Net Tangible Assets',
                        'Working Capital',
                        'Invested Capital',
                        'Tangible Book Value',
                        'Total Debt',
                        'Net Debt',
                        'Share Issued',
                        'Ordinary Shares Number',
                        'Treasury Shares Number',
                        ]

INCOMESTATEMENT_KEYWORDS = [
                        'Total Revenue',
                        'Operating Revenue',
                        'Excise Taxes',
                        'Cost of Revenue',
                        'Gross Profit',
                        'Operating Expense',
                        'Selling General and Administrative',
                        'General & Administrative Expense',
                        'Salaries and Wages',
                        'Other G and A',
                        'Depreciation Amortization Depletion',
                        'Depreciation & amortization',
                        'Amortization',
                        'Amortization of Intangibles',
                        'Operating Income',
                        'Net Non Operating Interest Income Expense',
                        'Interest Income Non Operating',
                        'Interest Expense Non Operating',
                        'Total Other Finance Cost',
                        'Other Income Expense',
                        'Special Income Charges',
                        'Impairment of Capital Assets',
                        'Other Non Operating Income Expenses',
                        'Pretax Income',
                        'Tax Provision',
                        'Earnings from Equity Interest Net of Tax',
                        'Net Income Common Stockholders',
                        'Net Income',
                        'Net Income Including Non-Controlling Interests',
                        'Net Income Continuous Operations',
                        'Minority Interests',
                        'Otherunder Preferred Stock Dividend',
                        'Diluted NI Available to Com Stockholders',
                        'Basic EPS',
                        'Diluted EPS',
                        'Basic Average Shares',
                        'Diluted Average Shares',
                        'Total Operating Income as Reported',
                        'Total Expenses',
                        'Net Income from Continuing & Discontinued Operation',
                        'Normalized Income',
                        'Interest Income',
                        'Interest Expense',
                        'Net Interest Income',
                        'EBIT',
                        'EBITDA',
                        'Reconciled Cost of Revenue',
                        'Reconciled Depreciation',
                        'Net Income from Continuing Operation Net Minority Interest',
                        'Total Unusual Items Excluding Goodwill',
                        'Total Unusual Items',
                        'Normalized EBITDA',
                        'Tax Rate for Calcs',
                        'Tax Effect of Unusual Items',
                        ]

CASHFLOW_KEYWORDS = [
                    'Operating Cash Flow',
                    'Cash Flow from Continuing Operating Activities',
                    'Net Income from Continuing Operations',
                    'Depreciation Amortization Depletion',
                    'Depreciation & amortization',
                    'Deferred Tax',
                    'Deferred Income Tax',
                    'Asset Impairment Charge',
                    'Other non-cash items',
                    'Change in working capital',
                    'Change in Receivables',
                    'Changes in Account Receivables',
                    'Change in Inventory',
                    'Change in Payables And Accrued Expense',
                    'Change in Payable',
                    'Change in Tax Payable',
                    'Change in Income Tax Payable',
                    'Change in Account Payable',
                    'Change in Accrued Expense',
                    'Change in Other Working Capital',
                    'Investing Cash Flow',
                    'Cash Flow from Continuing Investing Activities',
                    'Capital Expenditure Reported',
                    'Net Business Purchase And Sale',
                    'Purchase of Business',
                    'Net Investment Purchase And Sale',
                    'Net Other Investing Changes',
                    'Financing Cash Flow',
                    'Cash Flow from Continuing Financing Activities',
                    'Net Issuance Payments of Debt',
                    'Net Long Term Debt Issuance',
                    'Long Term Debt Issuance',
                    'Long Term Debt Payments',
                    'Net Short Term Debt Issuance',
                    'Short Term Debt Issuance',
                    'Short Term Debt Payments',
                    'Net Common Stock Issuance',
                    'Common Stock Payments',
                    'Cash Dividends Paid',
                    'Common Stock Dividend Paid',
                    'Net Other Financing Charges',
                    'End Cash Position',
                    'Changes in Cash',
                    'Effect of Exchange Rate Changes',
                    'Beginning Cash Position',
                    'Income Tax Paid Supplemental Data',
                    'Interest Paid Supplemental Data',
                    'Capital Expenditure',
                    'Issuance of Debt',
                    'Repayment of Debt',
                    'Repurchase of Capital Stock',
                    'Free Cash Flow',
                    ]